### ISSUE TITLE
Pull request on probonopd/AppImages

### ISSUE THREAD

**Issue by probonopd** [Barthalion/appimage-spotify#1]
Hi, great work, feel free to send a pull request to probonopd/AppImages.

**Comment by barthalion** [comment]
Hi, I certainly will next week, I have to test it on my laptop at work yet.

**Comment by probonopd** [comment]
Also see https://community.spotify.com/t5/Live-Ideas/Desktop-Other-Linux-Provide-Spotify-Desktop-Client-in-cross/idi-p/1337399
